### ISSUE TITLE
can't run from eclipse

### ISSUE THREAD

**Issue by sherifyounis** [frmichel/morph-xr2rml#8]
To override log4j configuration add JVM option: -Dlog4j.configuration=file:/home/.../your_log4j.properties
Loading log4j configuration: file:/E:/sherif%20sources/sherif%20thesis/dr%20fatma/morph-xr2rml-master/morph-xr2rml-master/morph-xr2rml-dist/target/classes/xr2rml-log4j.properties
2021-01-08 13:33:51 INFO  [main] (MorphRunner.scala:46) - Current directory    = E:\sherif sources\sherif thesis\dr fatma\morph-xr2rml-master\morph-xr2rml-master\morph-xr2rml-dist
2021-01-08 13:33:51 FATAL [main] (MorphRunner.scala:118) - An unexpected error occured: Missing argument for option: d
org.apache.commons.cli.MissingArgumentException: Missing argument for option: d
	at org.apache.commons.cli.DefaultParser.checkRequiredArgs(DefaultParser.java:211)
	at org.apache.commons.cli.DefaultParser.handleOption(DefaultParser.java:612)
	at org.apache.commons.cli.DefaultParser.handleLongOptionWithoutEqual(DefaultParser.java:415)
	at org.apache.commons.cli.DefaultParser.handleLongOption(DefaultParser.java:384)
	at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:239)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
	at fr.unice.i3s.morph.xr2rml.engine.MorphRunner$.main(MorphRunner.scala:62)
	at fr.unice.i3s.morph.xr2rml.engine.MorphRunner.main(MorphRunner.scala)

**Comment by sherifyounis** [comment]
can help me how to pass right arguments

**Comment by frmichel** [comment]
I'm wondering what the error message means: "Missing argument for option: d", what is this option d.
What is the command you have run?

The run command should be as documented in the README:
```
java -jar target/morph-xr2rml-dist-<version>-jar-with-dependencies.jar \
   --configDir <configuration directory> \
   --configFile <configuration file within this directory>
```

There might be a pb with the paths including blank characters : "sherif thesis\dr fatma". Try from a path without any blank.

PS: Although I don't mind answering your questions, basic politeness conventions (such as hello, please, thank you etc.) would be more than welcome. I would also appreciate a follow-up to know whether the answer solved your problem (I'm referring to your previous issue #7).

**Comment by sherifyounis** [comment]
Dear Mr. Frank,Hope this mail finds you well.
 Sorry for ignoring the basic conversations code, I really never meant it.🌹
 About my previous issue, I really wanted to thank you, but the command was solved and the window was closed. Didn't know where to send a feedback.
About the current issue, I will try a different path with no blanks.
Thanks a million for your time and consideration.And sorry once more.
Sherif Younis.
 
  On Mon., 11 Jan. 2021 at 2:42 pm, Franck Michel<notifications@github.com> wrote:   


I'm wondering what the error message means: "Missing argument for option: d", what is this option d.
What is the command you have run?

The run command should be as documented in the README:
java -jar target/morph-xr2rml-dist-<version>-jar-with-dependencies.jar \
   --configDir <configuration directory> \
   --configFile <configuration file within this directory>

There might be a pb with the paths including blank characters : "sherif thesis\dr fatma". Try from a path without any blank.

PS: Although I don't mind answering your questions, basic politeness conventions (such as hello, please, thank you etc.) would be more than welcome. And a follow-up if the answer solved your problem (I'm referring to your previous issue #7).

**Comment by frmichel** [comment]
> Sorry for ignoring the basic conversations code, I really never meant it.  

No problem ;)

> About my previous issue, I really wanted to thank you, but the command was solved and the window was closed. Didn't know where to send a feedback. 

Oh good to know, I thought it was always possible to add a comment even though the issue was close, my mistake.

> About the current issue, I will try a different path with no blanks.

Ok let me know. This time I'll leave the issue open ;)

**Comment by sherifyounis** [comment]
Dear Mr. frmichel,
I'm solving the above issue but I now face a new issue which as follows :

2021-01-11 12:20:54 FATAL [main] (MorphRunner.scala:113) - An error has occured: Error, non-normalized triples map: Students
es.upm.fi.dia.oeg.morph.base.exception.MorphException: Error, non-normalized triples map: Students
	at es.upm.fi.dia.oeg.morph.base.querytranslator.MorphBaseTriplePatternBinder.$anonfun$bindmTP$1(MorphBaseTriplePatternBinder.scala:230)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike.map(SetLike.scala:101)
	at scala.collection.SetLike.map$(SetLike.scala:101)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at es.upm.fi.dia.oeg.morph.base.querytranslator.MorphBaseTriplePatternBinder.bindmTP(MorphBaseTriplePatternBinder.scala:225)
	at es.upm.fi.dia.oeg.morph.base.querytranslator.MorphBaseTriplePatternBinder.bindm(MorphBaseTriplePatternBinder.scala:64)
	at fr.unice.i3s.morph.xr2rml.mongo.querytranslator.MorphMongoQueryTranslator.translate(MorphMongoQueryTranslator.scala:82)
	at es.upm.fi.dia.oeg.morph.base.querytranslator.MorphBaseQueryTranslator.translate(MorphBaseQueryTranslator.scala:95)
	at es.upm.fi.dia.oeg.morph.base.engine.MorphBaseRunner.runQuery(MorphBaseRunner.scala:81)
	at es.upm.fi.dia.oeg.morph.base.engine.MorphBaseRunner.run(MorphBaseRunner.scala:29)
	at fr.unice.i3s.morph.xr2rml.engine.MorphRunner$.main(MorphRunner.scala:97)
	at fr.unice.i3s.morph.xr2rml.engine.MorphRunner.main(MorphRunner.scala)

**Comment by frmichel** [comment]
Hi @sherifyounis, can you please copy the mapping file? Is it one of the example mappings, or your own?

**Comment by sherifyounis** [comment]
Dear Mr. Frmichel, 
Thanks for your help.
The mapping file is as follows:  

@prefix xrr: <http://i3s.unice.fr/xr2rml#> .
@prefix rr:  <http://www.w3.org/ns/r2rml#> .
@prefix ex:  <http://example.com/> .
@prefix rml: <http://semweb.mmlab.be/ns/rml#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<#Students>
    a rr:TriplesMap;
    xrr:logicalSource [
    	# Jongo needs strings in singles quotes (difference with MongoDB shell)
        xrr:query """db.students.find( { 'FullName' : {$exists: 1} } )""";
    ];
    rr:subjectMap [ 
    	rr:template "http://example.org/student/{$._id}";
		rr:class ex:Student, ex:Trainee;
    ];
  	# Implicit conversion of a boolean element
    rr:predicateObjectMap [
    	rr:predicate ex:isActive;
    	rr:objectMap [ xrr:reference "$.active" ];
    ];
  	# Implicit conversion of a integer element
    rr:predicateObjectMap [
    	rr:predicate ex:hasId;
    	rr:objectMap [ xrr:reference "$.id"; ];
    ];
   	# Generation of multiple RDF terms with language tag
    rr:predicateObjectMap [
    	rr:predicate ex:activity;
    	rr:objectMap [ xrr:reference "$.Hobbies.*.hobby"; rr:language "en" ];
    ];
	
   	# Generation of multiple RDF terms with variable language tag per term.
    # Almost the same as above but with nested term map to iterate on each hobby separately
    rr:predicateObjectMap [
    	rr:predicate ex:activityWithVariableLang;
    	rr:objectMap [ 
            xrr:reference "$.Hobbies.*";
            xrr:nestedTermMap [
				rr:termType rr:Literal;
                xrr:reference "$.hobby";
                rr:language "en";
                xrr:languageReference "$.lang"; 
            ]
        ]
    ];
	
	#--- Simple nested term map: bag of terms qualified with term type and datatype
    rr:predicateObjectMap [
    	rr:predicate ex:first_names;
    	rr:objectMap [
    		xrr:reference "$.FullName.FirstNames.*";
			rr:termType xrr:RdfBag;
    		xrr:nestedTermMap [
				rr:termType rr:Literal;
				rr:datatype xsd:string;
            ];
		];
	];
    
   	# Generation of multiple terms from a template, assembled as an RDF list,
	# and datatyped with a nested term map
    rr:predicateObjectMap [
    	rr:predicate ex:names;
    	rr:objectMap [
			rr:template "{$.FullName.FirstNames.*} {$.FullName.LastName}";
			rr:termType xrr:RdfList;
			xrr:nestedTermMap [
				rr:termType rr:Literal;
				rr:datatype xsd:string;
			];
		];
	];
	
   	# Generation of multiple terms from a template, assembled as an RDF list,
	# and datatyped with a nested term map.
	# The result is the same as in the previous predicateObjectMap but using a nested term map
	# to first select FullName elements (this is artificial since here there is only one
	# FullName element.
    rr:predicateObjectMap [
    	rr:predicate ex:namesAlt;
    	rr:objectMap [
    		xrr:reference "$.FullName";
    		xrr:nestedTermMap [
				rr:template "{$.FirstNames.*} {$.LastName}";
				rr:termType xrr:RdfList;
				xrr:nestedTermMap [
					rr:termType rr:Literal;
					rr:datatype xsd:string;
				];
            ];
		];
	].

**Comment by frmichel** [comment]
If I get it right, you are using the query rewriting mode (property query.file.path) with the mapping from the example_mongo folder. Right?

Folder example_mongo contains examples meant for the graph materialization mode only. Conversely, the example_mongo_rewriting folder contains examples that can work in query rewriting mode.
One difference is that for the query rewriting to work, mappings must be normalized first, as described in [1]:  "a normalized triples map contains exactly one predicate-object map with exactly one predicate map and one object map, and any rr:class property is replaced by an equivalent predicate-object map with a constant predicate rdf:type."

The mapping you use has an rr:class with 2 objects, it gets translated into a predicate-object map whose object map has 2 objects. Hence it is not normalized.

To fix this, you can either comment the line with "query.file.path=" from your morph.properties file, or use the mapping in the example_mongo_rewriting folder instead.

[1] Michel, Faron-Zucker, et Montagnat, « A Generic Mapping-Based Query Translation from SPARQL to Various Target Database Query Languages ». https://hal.archives-ouvertes.fr/hal-01280951

**Comment by sherifyounis** [comment]
Dear Mr frmichel;
Thank you for helping me. Issue solved

**Comment by frmichel** [comment]
Cool, you're welcome ;)
