### ISSUE TITLE
Null pointer exception in query translation mode

### ISSUE THREAD

**Issue by arenas-guerrero-julian** [frmichel/morph-xr2rml#9]
Hi,

The virtualization mode in Morph-xR2RML using the latest jar file results in the following null pointer exception:

```
java.lang.NullPointerException
    at org.apache.jena.query.ARQ.isTrue(ARQ.java:650)
    at org.apache.jena.sparql.lang.ParserBase.<init>(ParserBase.java:292)
    at org.apache.jena.sparql.lang.SPARQLParserBase.<init>(SPARQLParserBase.java:43)
    at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11Base.<init>(SPARQLParser11Base.java:22)
    at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.<init>(SPARQLParser11.java:4974)
    at org.apache.jena.sparql.lang.ParserSPARQL11.perform(ParserSPARQL11.java:91)
    at org.apache.jena.sparql.lang.ParserSPARQL11.parse$(ParserSPARQL11.java:52)
    at org.apache.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:34)
    at org.apache.jena.query.QueryFactory.parse(QueryFactory.java:147)
    at org.apache.jena.query.QueryFactory.create(QueryFactory.java:79)
    at org.apache.jena.query.QueryFactory.read(QueryFactory.java:220)
    at org.apache.jena.query.QueryFactory.read(QueryFactory.java:165)
    at es.upm.fi.dia.oeg.morph.base.engine.MorphBaseRunner.run(MorphBaseRunner.scala:28)
    at fr.unice.i3s.morph.xr2rml.engine.MorphRunner$.main(MorphRunner.scala:97)
    at fr.unice.i3s.morph.xr2rml.engine.MorphRunner.main(MorphRunner.scala)
```

Materialization mode is working fine :)

**Comment by frmichel** [comment]
Query translation mode in non-server mode, that is with property query.sparql set in morph.properties file.
Tested on morph-xr2rml-dist-1.3.1-jar-with-dependencies.jar.

**Comment by namedgraph** [comment]
Is this project abandoned?
